package com.broadridge.margin;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(841dc06a2945d4fa01799a29dd76a607)
 */
public class Diamention  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer fromAccount;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer fromBranch;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer toAccount;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Integer toBranch;

    public Diamention() {
    }

    public Diamention(java.lang.Integer fromAccount, java.lang.Integer toAccount, java.lang.Integer fromBranch, java.lang.Integer toBranch) {
        this.fromAccount = fromAccount;
        this.toAccount = toAccount;
        this.fromBranch = fromBranch;
        this.toBranch = toBranch;
    }


    
    public java.lang.Integer getFromAccount() {
        return this.fromAccount;
    }

    public void setFromAccount(java.lang.Integer fromAccount) {
        this.fromAccount = fromAccount;
    }
    
    public java.lang.Integer getFromBranch() {
        return this.fromBranch;
    }

    public void setFromBranch(java.lang.Integer fromBranch) {
        this.fromBranch = fromBranch;
    }
    
    public java.lang.Integer getToAccount() {
        return this.toAccount;
    }

    public void setToAccount(java.lang.Integer toAccount) {
        this.toAccount = toAccount;
    }
    
    public java.lang.Integer getToBranch() {
        return this.toBranch;
    }

    public void setToBranch(java.lang.Integer toBranch) {
        this.toBranch = toBranch;
    }
}