package com.broadridge.margin;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(c357a2b3d37d5d39bd1352a13770b55b)
 */
public class MarginProcessContext extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "account Id")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String accountId;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.util.Date businessDate;
    
    @org.kie.api.definition.type.Label(value = "cash call status")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String cashCallStatus;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String fedCallStatus;
    
    @org.kie.api.definition.type.Label(value = "user info")
    @org.kie.api.definition.type.Position(value = 2)
    private com.broadridge.margin.UserInfo user;
    
    @org.kie.api.definition.type.Position(value = 1)
    private boolean valid;

    public MarginProcessContext() {
    }

    public MarginProcessContext(java.util.Date businessDate, boolean valid, com.broadridge.margin.UserInfo user, java.lang.String accountId, java.lang.String fedCallStatus, java.lang.String cashCallStatus) {
        this.businessDate = businessDate;
        this.valid = valid;
        this.user = user;
        this.accountId = accountId;
        this.fedCallStatus = fedCallStatus;
        this.cashCallStatus = cashCallStatus;
    }


    
    public java.lang.String getAccountId() {
        return this.accountId;
    }

    public void setAccountId(java.lang.String accountId) {
        this.accountId = accountId;
    }
    
    public java.util.Date getBusinessDate() {
        return this.businessDate;
    }

    public void setBusinessDate(java.util.Date businessDate) {
        this.businessDate = businessDate;
    }
    
    public java.lang.String getCashCallStatus() {
        return this.cashCallStatus;
    }

    public void setCashCallStatus(java.lang.String cashCallStatus) {
        this.cashCallStatus = cashCallStatus;
    }
    
    public java.lang.String getFedCallStatus() {
        return this.fedCallStatus;
    }

    public void setFedCallStatus(java.lang.String fedCallStatus) {
        this.fedCallStatus = fedCallStatus;
    }
    
    public com.broadridge.margin.UserInfo getUser() {
        return this.user;
    }

    public void setUser(com.broadridge.margin.UserInfo user) {
        this.user = user;
    }
    
    public boolean isValid() {
        return this.valid;
    }

    public void setValid(boolean valid) {
        this.valid = valid;
    }
    public boolean isBusDateIsonOrAfterCurrentDate(){
		
		java.util.Calendar toDate = java.util.Calendar.getInstance();
		java.util.Calendar nowDate = java.util.Calendar.getInstance();
		nowDate.setTime(this.businessDate);
		
		boolean ret = ((this.businessDate != null ) && ( toDate.after(nowDate) || toDate.equals(nowDate) ));
		
		return ret;
		
	}
}