package com.broadridge.margin;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(0822bd92c44f91a97ec7bde30aa82b82)
 */
@org.kie.api.definition.type.Label(value = "User Info")
public class UserInfo extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Manager Id")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String mgrId;
    
    @org.kie.api.definition.type.Label(value = "User Id")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String userId;

    public UserInfo() {
    }

    public UserInfo(java.lang.String userId, java.lang.String mgrId) {
        this.userId = userId;
        this.mgrId = mgrId;
    }


    
    public java.lang.String getMgrId() {
        return this.mgrId;
    }

    public void setMgrId(java.lang.String mgrId) {
        this.mgrId = mgrId;
    }
    
    public java.lang.String getUserId() {
        return this.userId;
    }

    public void setUserId(java.lang.String userId) {
        this.userId = userId;
    }
}